version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: vgtpbx-postgres:latest
    container_name: vgtpbx-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-vgtpbx}
      PGDATA: /var/lib/postgresql/data/pgdata
      SWITCH_DB_PASSWORD: ${DATABASE_PASSWORD:-insecure12345}
    volumes:
      - vgtpbx-postgres-data:/var/lib/postgresql/data
      - type: bind
        source: ${PWD}/init-scripts
        target: /docker-entrypoint-initdb.d
        read_only: true
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - vgtpbx-network

volumes:
  vgtpbx-postgres-data:
    name: vgtpbx-postgres-data

networks:
  vgtpbx-network:
    name: vgtpbx-network
    driver: bridge